# Overview

Adding an additional analysis to the Tagirdzhanova et al. manuscript. The previous analysis cut off SRA searches in 2021 (2021.10.20), but added additional unpublished sequences from the collaborating authors which were eventually published in 2022/2023.

The goal of this secondary analysis is to check the findings of the manuscript, that a core group of taxa occur in the majority of published lichen genomes.

Many of these scripts are customized version of the original scripts generated by Gulnara Tagirdzhanova, and listed in the manuscript.

# Methods

To query the SRA, we used the [rentrez package in R](https://cran.r-project.org/web/packages/rentrez/vignettes/rentrez_tutorial.html). Since we were interested in lichen metagenomes, our search included the terms lichen or lichens in any field. We additionally searched for any records that included Pezizomycotina in the record's taxonomy. Since some lichens are submitted as 'lichen metagenome', we also searched for this term in the record's taxonomy. To make our results comparable to our earlier search, only metagenomes generated by Illumina and listed as 'whole genome sequencing' were included in our final set of candidate metagenomes. And finally, to reduce redundancy from the previously assembled data set, we only included metagenomes published after October 1st, 2021.

We also queried Web of Science for any genomes that did not appear in our initial dataset, and found 2 additional metagenomes. The missing records were all associated with publications that submitted their files to the SRA before October 2021, but published after. Therefore missed by both our search approaches.

Because our search terms included 'lichen' anywhere in the searchable fields, we manually confirmed the metagenomes were from a lichen. Genera from the candidate metagenomes were manually checked to ensure that only lichen genera remained, and organisms associated with a lichen (for example, a tardigrade living on a lichen) were eliminated.

To confirm that the candidate metagenomes were suitable, for every record we confirmed that the collection method was from the field (and not cultured) and the thalli were not aggressively washed. Lichen thalli cleaned of debris were not eliminated. When possible, this was done by finding the associated publication record, but when publications were not available (e.g. research grants) only those records that included this information in the sample file metadata were included.

The SRA search script can be found at `scripts/sra_search_clean.R`.

SRA files were downloaded using NCBI's [SRA Tools](https://github.com/ncbi/sra-tools). The script can be found at `scripts/sratools.sh`. Ensure the number of files downloaded matches the number of expected. Pre-fetch fails if files are >20 GB. The script is set to 21GB (which accomodated all files we needed)

With our final set of genomes, we ran [sourmash](https://sourmash.readthedocs.io/en/latest/) to check for duplicate genomes. We compared both the new metagenomes and the previously curated dataset. Any metagenome with a score of 1 would indicate that we had a duplicate metagenome. We found no duplicate metagenomes. The script for building 

To make our results comparable to the previously generated dataset, taxonomy was assigned by comparing and extracting known SSU barcoding regions from the metagenome to existing databases using [IDTAXA](http://www2.decipher.codes/Classification.html) (bacteria) and [Metaxa2](https://microbiology.se/software/metaxa2/) (all other taxa). Post identification, the presence/absence matrix was summarized to include the total number of metagenomes which contained the barcoding region and the relative percentage of the metagenomes.

# Running the scripts

Scripts are ordered by the steps required to run them. For example, the first script to run is labeled '01_...' while the second is '02...'. All scripts can be found in the `scripts/` directory. Below is the example of how to run the code. 

You need to start in the 'additional_survey' directory for the scripts to work out of the box. You also need to set your SRA Toolkit cache in `02_sratools.download.sh` before proceeding. When filesize allowed, I've included the outputs in the results folder. I've also included the IDTAXA training data as a .RDS file in `data/db`. 

```
cd additional_survey

Rscript ./scripts/01_sra_search_clean.R

./scripts/02_sratools_download.sh ./output/sra_accession_for_sra_download.txt

./scripts/03_sourmash_script.sh ./output/sra_accession_for_sra_download.txt

./scripts/04_metaxa_run.sh ./output/sra_accession_for_sra_download.txt

./scripts/05_metaxa_ttt_run.sh 

Rscipt ./scripts/06_idtaxa_compiling_db.R

Rscript ./scripts/07_idtaxa_run.R

Rscript ./scripts/08_idtaxa_summarizing.R

```